### ISSUE TITLE
Missing camel-jackson dependency at runtime

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-integration-runtime#2]
As reported by @jludvice when a new integration is run Camel route start fails with:

    Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: dataformat://json-jackson:marshal due to: Cannot find data format with name: json-jackson
            at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:678)
            at io.syndesis.integration.runtime.components.json.JsonEndpoint.doStart(JsonEndpoint.java:77)
            at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)

**Comment by jludvice** [comment]
CC @dsimansk

**Comment by rhuss** [comment]
Should be fixed now.
