### ISSUE TITLE
Exception in a simple Twitter -> Salesforce integration

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-integration-runtime#6]
```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
12:56:57.093 [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.apache.camel.spring.boot.CamelSpringBootInitializationException: org.apache.camel.FailedToCreateRouteException: Failed to create route flow1: Route(flow1)[[From[twitter-mention]] -> [To[json:marshal], T... because of Failed to resolve endpoint: dataformat://json-jackson:marshal due to: Cannot find data format with name: json-jackson
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:186)
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at io.syndesis.example.Application.main(Application.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route flow1: Route(flow1)[[From[twitter-mention]] -> [To[json:marshal], T... because of Failed to resolve endpoint: dataformat://json-jackson:marshal due to: Cannot find data format with name: json-jackson
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:147)
	at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3715)
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3622)
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3408)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3262)
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:201)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3046)
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3042)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3065)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3042)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:2980)
	at org.apache.camel.spring.boot.RoutesCollector.maybeStart(RoutesCollector.java:203)
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:178)
	... 23 common frames omitted
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: dataformat://json-jackson:marshal due to: Cannot find data format with name: json-jackson
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:678)
	at io.syndesis.integration.runtime.components.json.JsonEndpoint.doStart(JsonEndpoint.java:77)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.processor.SendProcessor.doStart(SendProcessor.java:236)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
	at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:80)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
	at org.apache.camel.processor.RedeliveryErrorHandler.doStart(RedeliveryErrorHandler.java:1447)
	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:44)
	at org.apache.camel.support.ChildServiceSupport.start(ChildServiceSupport.java:31)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
	at org.apache.camel.processor.interceptor.DefaultChannel.doStart(DefaultChannel.java:156)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:62)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
	at org.apache.camel.processor.MulticastProcessor.doStart(MulticastProcessor.java:1163)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:60)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:104)
	at org.apache.camel.util.ServiceHelper.startServices(ServiceHelper.java:90)
	at org.apache.camel.processor.DelegateAsyncProcessor.doStart(DelegateAsyncProcessor.java:80)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75)
	at org.apache.camel.impl.RouteService.startChildService(RouteService.java:364)
	at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:196)
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:145)
	... 36 common frames omitted
Caused by: java.lang.IllegalArgumentException: Cannot find data format with name: json-jackson
	at org.apache.camel.component.dataformat.DataFormatComponent.createEndpoint(DataFormatComponent.java:49)
	at org.apache.camel.impl.DefaultComponent.createEndpoint(DefaultComponent.java:116)
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:631)
	... 78 common frames omitted
12:56:57.096 [main] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3d04a311: startup date [Wed Jul 26 12:56:48 UTC 2017]; root of context hierarchy
12:56:57.099 [main] INFO  o.s.c.s.DefaultLifecycleProcessor - Stopping beans in phase 0
12:56:57.100 [main] INFO  o.s.b.a.e.jmx.EndpointMBeanExporter - Unregistering JMX-exposed beans on shutdown
12:56:57.101 [main] INFO  o.s.b.a.e.jmx.EndpointMBeanExporter - Unregistering JMX-exposed beans
12:56:57.102 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Unregistering JMX-exposed beans on shutdown
```

with the integration from https://github.com/rhuss/twitter-test

**Comment by zregvart** [comment]
I think this was fixed with syndesisio/syndesis-integration-runtime#5, using older version?

**Comment by rhuss** [comment]
Good point, I will retry.

**Comment by jimmidyson** [comment]
Yeah the [commit](https://github.com/syndesisio/syndesis-integration-runtime/commit/34f43bcbdbf2639be5791a63e5e74f3957c8eb7a) hasn't been released... Let me do that now.

**Comment by jimmidyson** [comment]
Or at least tags haven't been pushed.... Let me re-release just to be on the safe side.

**Comment by jimmidyson** [comment]
FYI the fix was actually in https://github.com/syndesisio/syndesis-integration-runtime/commit/edd9dc8d689c3f777fa6d13495214e6a144c0d9c which wasn't released either... Doing so now.

**Comment by jimmidyson** [comment]
OK tagged properly as v0.1.2 and waiting sync to maven central... try in about 20 minutes or so with updated version please.

**Comment by jimmidyson** [comment]
@rhuss Did you manage to confirm this was fixed or is it still an issue?

**Comment by rhuss** [comment]
works now for me, too. Thanks !
